version: "3.8"

services:
  db:
    image: postgres:14.1
    container_name: postgres
    environment:
      POSTGRES_USER: nikenpatel
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nikenpatel
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nikenpatel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend-network
    restart: unless-stopped

  api:
    build:
      context: ./backend
    container_name: nikenpatel-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nikenpatel
      SPRING_DATASOURCE_USERNAME: nikenpatel
      SPRING_DATASOURCE_PASSWORD: yourpassword
    depends_on:
      - db
    ports:
      - "8088:8080"
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/react
      args:
        api_base_url: http://localhost:8088
    container_name: nikenpatel-react
    depends_on:
      - api
    ports:
      - "80:5173"
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  db-data: {}