services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: nikenpatel
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nikenpatel
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  nikenpatel-api:
    container_name: nikenpatel-api
    image: nikenpatel/nikenpatel-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nikenpatel
      SPRING_DATASOURCE_USERNAME: nikenpatel
      SPRING_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  nikenpatel-react:
    container_name: nikenpatel-react
    image: nikenpatel/nikenpatel-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - nikenpatel-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
