aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://<rds-endpoint>.us-east-2.rds.amazonaws.com:5432/ebdb
    username: nikenpatel/full-stack/postgres
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
